### ISSUE TITLE
对比实验咨询

### ISSUE THREAD

**Issue by dadapongI6** [Xiaohan-Chen/TFPred#1]
作者您好！感谢您分享本文工作与算法，对我的工作有很大的启发。在您的代码库我没找到对比方法的代码，比如SimCLR、MoCo、BYOL、SimSiam等。我想试一下对比实验的方法，但网上的相关代码质量参差不齐，且用于信号数据的代码很少，所以冒昧问一下您可不可以再公开一下本文的对比方法的代码。

**Comment by Xiaohan-Chen** [comment]
您好，感谢对我们的研究工作感兴趣，也十分高兴我们的工作可以为您提供一点参考和帮助。您所提到的代码原作者均已公开他们的源代码，你可以在相应的论文中找到。
