### ISSUE TITLE
您好，能不能上传一下对比的算法，比如Meanteacher，SimCLR这些？

### ISSUE THREAD

**Issue by Bkamie** [Xiaohan-Chen/TFPred#2]
我是一个少标签样本故障诊断方向的初学者，读了您的文章，觉得写的很好,编程也很厉害，想向您学习。只是我刚入门，编程水平一般，还没办法复现那么多代码来做对比实验。如果方便的话能不能把您做对比实验的这些方法也分享一下？如果不方便的话也没关系，非常感谢您的分享，使我在学习的路上少走了一些弯路。

**Comment by Xiaohan-Chen** [comment]
您好，非常感谢您对我们的研究工作感兴趣，并给予了肯定。文中所提到的方法您均可在原论文中找到作者的公开代码，您可以访问他们的论文获取。
另外，如果您对few-shot问题感兴趣，还可以访问我们另一个开源库: [few-shot-fault-diagnosis](https://github.com/Xiaohan-Chen/few-shot-fault-diagnosis)，希望能对您有所帮助。
