### ISSUE TITLE
about prediction head Q(·)

### ISSUE THREAD

**Issue by blackjiang-xin** [Xiaohan-Chen/TFPred#3]
您好，我想请问为什么频域的特征还需要经过一个prediction head Q(·)，怎么确保经过prediction head Q(·)的特征和zt还具有相关性。

**Comment by Xiaohan-Chen** [comment]
The motivation for using the prediction head Q(·) from the paper "Bootstrap Your Own Latent: A New Approach to Self-Supervised Learning," in which the authors used a prediction head to predict the augmented offline gadgets.

In our work, we use the time encoder and the frequency encoder to extract time and frequency domain features, respectively. To model the correlation between time domain features and frequency domain features, we use the prediction head Q(·) to project the frequency domain features into the time domain, and apply the cross-correlation loss function to guide the model to learn time and frequency features with correlation from raw unlabeled signals. We hope the comments can address your concern.
